// 63.deploy-django-rest-framework-and-vue-js-together-with-apache-web-server/django-rest-framework-and-vue-js-project/frontend/src/App.vue
<template>
  <div class="App">
    <h1>Connect Vue JS to Django</h1>
    <div v-for="(student, index) in students" :key="index">
      <h2>{{ student.stuname }} {{ student.email }}</h2>
    </div>
  </div>
</template>

<script lang="ts">
import { ref, onMounted } from "vue";
import axios from "axios";

interface Student {
  id: number;
  stuname: string;
  email: string;
}

export default {
  name: "App",
  setup() {
    const students = ref<Student[]>([]);

    const getAllStudents = async () => {
      try {
        const response = await axios.get<Student[]>("http://backend.django-rest-framework-and-vue-js-project.com/api/student/");
        students.value = response.data;
      } catch (error) {
        console.error(error);
      }
    };

    onMounted(() => {
      getAllStudents();
    });

    return {
      students,
    };
  },
};
</script>

<style>
.App {
  text-align: center;
}
</style>

// 59.deploy-django-rest-framework-and-react-js-together-with-apache-web-server/django-rest-framework-and-react-js-project/frontend/src/App.js
import './App.css';
import { useState, useEffect } from "react";
import axios from "axios";

function App() {
  const [students, setStudents] = useState([]);

  useEffect(() => {
    async function getAllStudent() {
      try {
        const students = await axios.get("http://backend.django-rest-framework-and-react-js-project.com/api/student/");
        console.log(students.data);
        setStudents(students.data);
      } catch (error) {
        console.log(error);
      }
    }
    getAllStudent();
  }, []);

  return (
    <div className="App">
      <h1>Connect React JS to Django</h1>
      {
        students.map((student, i) => {
          return (
            <h2 key={i}>{student.stuname} {student.email}</h2>
          )
        })
      }
    </div>
  );
}

export default App;
